.\" NÃO MODIFICAR ESSE ARQUIVO MANUALMENTE
.TH COMITAR "1" "Julho de 2025" "Versao 2.0.1" "Manual do Usuario"
.SH NOME
comitar \- Script de commits semânticos com emojis, validações e changelog.
.SH SINOPSE
.B comitar
[\fIOPCAO\fR]...
.br
.SH RESUMO
Facilita e padroniza o uso de mensagens de commit no Git, com suporte a emojis, convenções semânticas, geração automática de changelog e configurações personalizadas via arquivo local.
.SH DESCRICAO
.PP
O script \fBcomitar\fR foi criado para promover boas práticas no uso de mensagens de commit, seguindo o padrão \fIConventional Commits\fR.
Ele inclui:
.IP \[bu] 2
Lista de tipos de commit com emojis personalizados
.IP \[bu]
Validação da mensagem antes do envio
.IP \[bu]
Geração automática de changelog
.IP \[bu]
Criação de tags por tipo
.IP \[bu]
Suporte a configurações locais com \fBcomitar.json\fR
.SH OPCOES
.TP
\fB-h\fR, \fB--help\fR
Exibe a tela de ajuda com as opções disponíveis.
.TP
\fB-V\fR, \fB--version\fR
Exibe a versão atual do script comitar.
.TP
\fB--commit\fR
Inicia o processo interativo para criação de um commit semântico.
.TP
\fB--config\fR, \fB-c\fR
Abre o menu interativo de configurações.
.TP
\fB--install-hook\fR
Instala o hook de validação de mensagens no repositório atual.
.TP
\fB--undo\fR
Desfaz o último commit (mesmo que já tenha sido enviado com \fIgit push\fR).
.TP
\fB--changelog\fR
Gera o changelog com base no histórico de commits.
.TP
\fB--upgrade\fR
Atualiza os arquivos do Comitar para a versão mais recente.
.TP
\fB--uninstall\fR
Remove completamente o Comitar e seus arquivos relacionados.
.SH EXEMPLOS
.PP
Criar um commit com tipo \fBfeat\fR e emoji correspondente:
.IP
\f(CW$ comitar\fR
.PP
Exibir ajuda:
.IP
\f(CW$ comitar --help\fR
.PP
Verificar a versão:
.IP
\f(CW$ comitar -V\fR
.PP
Abrir menu de configurações:
.IP
\f(CW$ comitar --config\fR
.PP
Instalar o hook de commit-msg:
.IP
\f(CW$ comitar --install-hook\fR
.SH REQUISITOS
Git, Bash 4+, permissão de execução, ambiente Unix-like, jq.
.SH LICENCA
Este projeto é software livre e está licenciado sob a \fBGNU General Public License v3.0\fR.
Veja o arquivo LICENSE para mais detalhes.
.SH CONTRIBUICAO
Sugestões, correções e melhorias são bem-vindas!
Acesse: \fIhttps://github.com/ketteiGustavo/comitar\fR
.SH AUTOR
Escrito por Luiz Gustavo <luizg.devlx@gmail.com>
